# Generated by Django 3.2 on 2022-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0005_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='uuid',
            field=models.CharField(max_length=256),
        ),
    ]
