# Generated by Django 3.2 on 2022-01-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0006_alter_test_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='uuid',
            field=models.CharField(max_length=500, verbose_name='유유아디'),
        ),
    ]
