# Generated by Django 3.2 on 2022-01-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0007_alter_test_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='uuid',
            field=models.BinaryField(max_length=16),
        ),
    ]
