# Generated by Django 3.2 on 2022-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0011_rename_post_id_test_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='uuid',
        ),
        migrations.AddField(
            model_name='test',
            name='shoe_id',
            field=models.CharField(default=1, max_length=256, verbose_name='브랜드'),
            preserve_default=False,
        ),
    ]
